// LM-FRAGMENT injectStyles() - all menu CSS
// LM-FRAGMENT source fragment of lumen_menu, assembled in order into ONE IIFE
// LM-FRAGMENT by boot.lua (read_menu_js). Not a standalone module. See 01-core.js.


  // ── styles (match the native Steam Settings window exactly) ────────────────
  function injectStyles() {
    if (document.getElementById(STYLE_ID)) return;
    var s = document.createElement("style");
    s.id = STYLE_ID;
    s.textContent = [
      "#" + BTN_ID + "{display:inline-flex;align-items:center;justify-content:center;",
      "cursor:pointer;font-size:13px;line-height:1;padding:2px 8px;margin:0 2px;",
      "opacity:.8;-webkit-app-region:no-drag;user-select:none;border-radius:3px;}",
      "#" + BTN_ID + ":hover{opacity:1;background:rgba(255,255,255,.08);}",
      "#" + OVERLAY_ID + "{position:fixed;inset:0;z-index:99999;display:flex;",
      "align-items:center;justify-content:center;background:rgba(0,0,0,.55);",
      "font-family:'Motiva Sans',Arial,Helvetica,sans-serif;}",
      // window
      ".lumen-win{display:flex;width:900px;max-width:94vw;height:620px;max-height:88vh;",
      "border-radius:4px;overflow:hidden;box-shadow:0 20px 60px rgba(0,0,0,.6);",
      "border:1px solid rgba(0,0,0,.5);}",
      // sidebar
      ".lumen-side{flex:0 0 200px;background:#2a2d34;display:flex;flex-direction:column;",
      "padding-top:8px;overflow-y:auto;overscroll-behavior:contain;}",
      ".lumen-side-title{color:#1a9fff;font-size:17px;font-weight:700;text-transform:uppercase;",
      "padding:14px 24px 16px;}",
      ".lumen-tab{display:flex;align-items:center;gap:12px;padding:10px 8px 10px 24px;",
      "height:20px;color:#b8bcbf;font-size:14px;cursor:pointer;}",
      ".lumen-tab:hover{background:rgba(255,255,255,.04);}",
      ".lumen-tab.active{background:#3d4450;color:#fff;}",
      ".lumen-tab .ico{display:inline-flex;width:16px;height:16px;flex:0 0 16px;}",
      // content
      ".lumen-content{flex:1;background:#25282e;background-image:radial-gradient(circle at left top,",
      "rgba(74,81,92,.4) 0%,rgba(75,81,92,0) 60%);display:flex;flex-direction:column;overflow:hidden;}",
      ".lumen-ctop{display:flex;align-items:center;padding:24px 24px 14px;}",
      ".lumen-ctop .h{flex:1;color:#fff;font-size:22px;font-weight:700;}",
      ".lumen-exp{display:inline-block;vertical-align:middle;margin-left:10px;font-size:10px;",
      "font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:#ffb84d;",
      "background:#3a2f1a;padding:2px 8px;border-radius:10px;}",
      ".lumen-info{display:inline-flex;vertical-align:middle;margin-left:6px;width:16px;height:16px;",
      "align-items:center;justify-content:center;font-size:11px;font-weight:700;font-style:italic;",
      "cursor:pointer;color:#8f98a0;border:1px solid #4a5663;border-radius:50%;}",
      ".lumen-info:hover{color:#fff;border-color:#8f98a0;}",
      ".lumen-ctop .x{cursor:pointer;color:#b8bcbf;font-size:18px;padding:2px 8px;border-radius:3px;}",
      ".lumen-ctop .x:hover{color:#fff;background:rgba(255,255,255,.08);}",
      ".lumen-ctop .reset{cursor:pointer;color:#b8bcbf;font-size:12px;font-weight:600;" +
        "margin-right:10px;padding:5px 12px;border-radius:4px;white-space:nowrap;" +
        "border:1px solid rgba(255,255,255,.14);transition:.12s;}",
      ".lumen-ctop .reset:hover{color:#fff;background:rgba(255,255,255,.08);}",
      ".lumen-ctop .reset.confirm{color:#ffb84d;border-color:#ffb84d;}",
      ".lumen-body{padding:0 24px 22px;overflow-y:auto;overflow-x:hidden;overscroll-behavior:contain;}",
      ".lumen-note{color:#8f98a0;font-size:12px;padding:0 0 10px;line-height:1.4;}",
      ".lumen-row{display:flex;align-items:flex-start;gap:14px;padding:12px 2px;",
      "border-bottom:1px solid rgba(255,255,255,.06);}",
      ".lumen-lblwrap{flex:1;display:flex;flex-direction:column;gap:4px;min-width:0;}",
      ".lumen-row .lbl{color:#dcdedf;font-size:14px;}",
      ".lumen-desc{color:#8f98a0;font-size:12px;line-height:1.45;}",
      ".lumen-line{font-size:12px;line-height:1.45;display:flex;gap:6px;align-items:flex-start;}",
      ".lumen-line .i{flex:0 0 auto;}",
      ".lumen-line.info{color:#66c0f4;}",
      ".lumen-line.advanced{color:#e0b341;}",
      ".lumen-line.danger{color:#ec5c5c;}",
      ".lumen-ctrl{flex:0 0 auto;margin-top:1px;display:inline-flex;align-items:center;}",
      ".lumen-row input[type=text],.lumen-row input[type=number],.lumen-row select{",
      "background:#1a1d23;color:#dcdedf;border:1px solid #3d4450;border-radius:3px;",
      "padding:6px 8px;min-width:130px;font-size:13px;font-family:inherit;}",
      ".lumen-row select:hover,.lumen-row input:hover{border-color:#4a5663;}",
      ".lumen-sw{position:relative;display:inline-block;width:38px;height:20px;flex:0 0 auto;}",
      ".lumen-sw input{opacity:0;width:0;height:0;position:absolute;}",
      ".lumen-sw .sl{position:absolute;inset:0;background:#3d4450;border-radius:20px;transition:.15s;cursor:pointer;}",
      ".lumen-sw .sl:before{content:'';position:absolute;width:14px;height:14px;left:3px;top:3px;",
      "background:#fff;border-radius:50%;transition:.15s;}",
      ".lumen-sw input:checked + .sl{background:#1a9fff;}",
      ".lumen-sw input:checked + .sl:before{transform:translateX(18px);}",
      ".lumen-err{color:#ec5c5c;font-size:13px;padding:12px 0;}",
      // Game Updates tab
      ".lumen-gu-search{width:100%;box-sizing:border-box;background:#1a1d23;color:#dcdedf;",
      "border:1px solid #3d4450;border-radius:3px;padding:8px 10px;font-size:13px;",
      "font-family:inherit;margin:0 0 12px;}",
      ".lumen-gu-search:focus{outline:none;border-color:#1a9fff;}",
      ".lumen-gu-actions{display:flex;justify-content:flex-end;margin:0 0 12px;}",
      ".lumen-load-lua{font-size:13px;}",
      ".lumen-game{border-bottom:1px solid rgba(255,255,255,.06);}",
      ".lumen-game-head{display:flex;align-items:center;gap:12px;padding:10px 2px;cursor:pointer;}",
      ".lumen-game-head:hover{background:rgba(255,255,255,.03);}",
      ".lumen-cap{flex:0 0 auto;width:92px;height:43px;border-radius:3px;object-fit:cover;",
      "background:#1a1d23;}",
      ".lumen-game-meta{flex:1;min-width:0;display:flex;flex-direction:column;gap:2px;}",
      ".lumen-game-name{color:#dcdedf;font-size:14px;white-space:nowrap;overflow:hidden;",
      "text-overflow:ellipsis;}",
      ".lumen-game-sub{color:#8f98a0;font-size:11px;}",
      ".lumen-badge{display:inline-block;font-size:10px;font-weight:700;text-transform:uppercase;",
      "padding:2px 6px;border-radius:3px;margin-left:6px;vertical-align:middle;}",
      ".lumen-badge.lock{background:#3a2f1a;color:#ffb84d;}",
      ".lumen-badge.cur{background:#1a3a24;color:#6fd08c;}",
      ".lumen-badge.lt{background:#1a2c3a;color:#66c0f4;}",
      ".lumen-adv{flex:0 0 auto;color:#5c6370;font-size:11px;padding:2px 6px;",
      "cursor:pointer;white-space:nowrap;align-self:flex-start;}",
      ".lumen-adv:hover{color:#a0a6ad;text-decoration:underline;}",
      ".lumen-import{color:#66c0f4;}",
      ".lumen-import:hover{color:#8fd0ff;}",
      ".lumen-more{color:#66c0f4;font-size:12px;cursor:pointer;padding:6px 8px 4px 12px;",
      "user-select:none;}",
      ".lumen-more:hover{text-decoration:underline;}",
      ".lumen-vers{padding:4px 2px 10px 104px;display:flex;flex-direction:column;gap:2px;}",
      ".lumen-ver{display:flex;align-items:center;gap:10px;padding:6px 8px;border-radius:3px;",
      "cursor:pointer;font-size:13px;color:#cdd1d4;}",
      ".lumen-ver:hover{background:rgba(255,255,255,.05);}",
      ".lumen-ver.sel{background:#2b3340;}",
      ".lumen-ver .dot{flex:0 0 auto;width:12px;height:12px;border-radius:50%;border:2px solid #6b7280;}",
      ".lumen-ver.sel .dot{border-color:#1a9fff;background:#1a9fff;}",
      ".lumen-ver .vgid{color:#8f98a0;font-size:11px;font-family:monospace;}",
      ".lumen-del{margin-left:auto;flex:0 0 auto;cursor:pointer;color:#6b7280;",
      "font-size:13px;padding:2px 8px;border-radius:3px;opacity:0;transition:.12s;}",
      ".lumen-ver:hover .lumen-del{opacity:1;}",
      ".lumen-del:hover{color:#ec5c5c;background:rgba(236,92,92,.12);}",
      ".lumen-back{display:inline-flex;align-items:center;gap:6px;cursor:pointer;color:#b8bcbf;",
      "font-size:13px;}",
      ".lumen-back:hover{color:#fff;}",
      ".lumen-sub-title{color:#fff;font-size:16px;font-weight:700;margin:10px 0 2px;}",
      ".lumen-empty{color:#8f98a0;font-size:13px;padding:20px 4px;text-align:center;}",
      // About tab
      ".lumen-about-intro{color:#8f98a0;font-size:12px;padding:0 0 14px;line-height:1.4;}",
      ".lumen-about-ver{display:flex;align-items:center;gap:12px;padding:12px 2px;",
      "border-bottom:1px solid rgba(255,255,255,.06);}",
      ".lumen-about-ver .nm{flex:1;min-width:0;color:#dcdedf;font-size:14px;font-weight:600;}",
      ".lumen-about-ver .vv{color:#8f98a0;font-size:12px;font-family:monospace;margin-top:3px;",
      "font-weight:400;}",
      ".lumen-about-state{flex:0 0 auto;font-size:11px;font-weight:700;text-transform:uppercase;",
      "letter-spacing:.4px;padding:3px 9px;border-radius:10px;white-space:nowrap;}",
      ".lumen-about-state.cur{background:#1a3a24;color:#6fd08c;}",
      ".lumen-about-state.upd{background:#3a2f1a;color:#ffb84d;}",
      ".lumen-about-state.unk{background:#2b303a;color:#8f98a0;}",
      ".lumen-about-actions{margin-top:22px;display:flex;flex-direction:column;gap:16px;}",
      ".lumen-about-act{background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.08);",
      "border-radius:8px;padding:16px 18px;display:flex;align-items:center;gap:16px;}",
      ".lumen-about-act .txt{flex:1;min-width:0;}",
      ".lumen-about-act .at{color:#dcdedf;font-size:14px;font-weight:600;margin-bottom:4px;}",
      ".lumen-about-act .ad{color:#8f98a0;font-size:12px;line-height:1.45;}",
      ".lumen-about-btn{flex:0 0 auto;cursor:pointer;font-size:13px;font-weight:600;",
      "padding:9px 18px;border-radius:4px;border:1px solid #1a9fff;background:#1a9fff;",
      "color:#fff;white-space:nowrap;transition:.12s;}",
      ".lumen-about-btn:hover{background:#3cb0ff;border-color:#3cb0ff;}",
      ".lumen-about-btn.confirm{background:#e0922f;border-color:#e0922f;}",
      ".lumen-about-btn.busy{opacity:.6;pointer-events:none;}",
      ".lumen-about-credit{margin-top:26px;text-align:center;color:#5c6370;font-size:11px;",
      "letter-spacing:.3px;}",
      ".lumen-about-credit a{color:#66c0f4;text-decoration:none;}",
      ".lumen-about-credit a:hover{text-decoration:underline;}",
      ".lumen-about-right{flex:0 0 auto;display:inline-flex;align-items:center;min-width:90px;",
      "justify-content:flex-end;}",
      // loading spinner (version line + state pill while versions are fetched)
      ".lumen-spin{display:inline-block;width:14px;height:14px;box-sizing:border-box;",
      "border:2px solid rgba(255,255,255,.16);border-top-color:#9aa3ab;border-radius:50%;",
      "animation:lumen-rot .7s linear infinite;vertical-align:middle;}",
      "@keyframes lumen-rot{to{transform:rotate(360deg);}}",
      // confirm modal (validate prompt) — sits above the settings overlay
      ".lumen-modal-back{position:fixed;inset:0;z-index:100000;display:flex;",
      "align-items:center;justify-content:center;background:rgba(0,0,0,.6);",
      "font-family:'Motiva Sans',Arial,Helvetica,sans-serif;}",
      ".lumen-modal{width:420px;max-width:90vw;background:#23262d;border-radius:4px;",
      "border:1px solid rgba(0,0,0,.5);box-shadow:0 16px 48px rgba(0,0,0,.6);",
      "padding:22px 24px 18px;}",
      ".lumen-modal .mt{color:#fff;font-size:17px;font-weight:700;margin-bottom:10px;}",
      ".lumen-modal .mb{color:#b8bcbf;font-size:13px;line-height:1.5;margin-bottom:18px;}",
      ".lumen-modal .mrow{display:flex;justify-content:flex-end;gap:10px;}",
      ".lumen-mbtn{cursor:pointer;font-size:13px;font-weight:600;padding:8px 16px;",
      "border-radius:4px;border:1px solid rgba(255,255,255,.14);color:#b8bcbf;",
      "background:transparent;transition:.12s;}",
      ".lumen-mbtn:hover{color:#fff;background:rgba(255,255,255,.08);}",
      ".lumen-mbtn.primary{background:#1a9fff;border-color:#1a9fff;color:#fff;}",
      ".lumen-mbtn.primary:hover{background:#3cb0ff;border-color:#3cb0ff;}",
    ].join("");
    (document.head || document.documentElement).appendChild(s);
  }

